### ISSUE TITLE
Support Prometheus basic auth

### ISSUE THREAD

**Issue by yonimoses** [kfdm/promql-guard#9]
Hi
Any chance to support authentication in the upstream Prometheus server configuration.
We’ve got authorization proxy before our Prometheus with authorization header.

**Comment by kfdm** [comment]
Could you be more specific ? You would like support for a different authorization proxy that sits in front of Prometheus ?

query -> promql-guard -> auth -> prometheus 
or
query -> auth -> promql-guard -> prometheus

**Comment by yonimoses** [comment]
I was actually thought of the first case you mentioned,query->guard-> prom, since our Prometheus is behind oauth proxy, but the second one can be nice addition as well;)

**Comment by kfdm** [comment]
I am not familiar with oauth proxy. Can you link me to some information about how it works ?

**Comment by yonimoses** [comment]
https://github.com/openshift/oauth-proxy

but leaving the oauth proxy aside (cause it's for humans) the fact that redhat deploys prom behind it, enforces an authorization to prom. hence we need support to send "Authorization" header when querying prometheus.

**Comment by kfdm** [comment]
One thing I can probably do without too much difficulty, is allow passing additional headers upstream. So the config would look something like

```
# Example Configuration
# htpasswd is used for tenant passwords
htpasswd: guard.htpasswd

# each tenant can then be configured with required matchers
hosts:
  - username: tenantA
    prometheus:
      upstream: http://localhost:9090
      matcher: '{service="tenantA"}'
      headers:
         authorization: token foobar
```

or something similar to this. Do you think this would work for your use case ? In this design you would still need to have a htpasswd file for promql-guard itself.

`query -> promql-guard -> oauth proxy -> prometheus`
